/**
 * 直接从 artifacts 同步 ABI 到前端
 * 这个脚本从 hardhat artifacts 读取编译后的合约 ABI，
 * 并将其同步到 Next.js 前端的 contracts 文件夹
 */

import * as fs from "fs";
import * as path from "path";
import prettier from "prettier";

const ARTIFACTS_DIR = "./artifacts/contracts";
const DEPLOYMENTS_DIR = "./deployments/localhost";
const TARGET_DIR = "../nextjs/contracts/";

interface ContractArtifact {
  abi: any[];
  bytecode: string;
  deployedBytecode: string;
}

interface DeploymentInfo {
  address: string;
  abi: any[];
}

async function syncAbiToFrontend() {
  console.log("🔄 Starting ABI sync from artifacts to frontend...");

  // 读取部署信息以获取合约地址
  const deployments: Record<string, DeploymentInfo> = {};
  
  if (fs.existsSync(DEPLOYMENTS_DIR)) {
    const files = fs.readdirSync(DEPLOYMENTS_DIR);
    
    for (const file of files) {
      if (file.endsWith(".json") && file !== ".chainId") {
        const contractName = file.replace(".json", "");
        const deploymentPath = path.join(DEPLOYMENTS_DIR, file);
        const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf-8"));
        
        deployments[contractName] = {
          address: deployment.address,
          abi: deployment.abi,
        };
        
        console.log(`✅ Found deployment: ${contractName} at ${deployment.address}`);
      }
    }
  }

  // 读取链 ID
  const chainIdPath = path.join(DEPLOYMENTS_DIR, ".chainId");
  const chainId = fs.existsSync(chainIdPath) 
    ? fs.readFileSync(chainIdPath, "utf-8").trim() 
    : "1337";

  console.log(`📡 Chain ID: ${chainId}`);

  // 构建输出对象
  const output: Record<string, any> = {};
  output[chainId] = {};

  for (const [contractName, deployment] of Object.entries(deployments)) {
    output[chainId][contractName] = {
      address: deployment.address,
      abi: deployment.abi,
      inheritedFunctions: {},
      deployedOnBlock: 0,
    };
  }

  // 生成 TypeScript 文件
  const fileContent = Object.entries(output).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }

  const targetPath = path.join(TARGET_DIR, "deployedContracts.ts");
  
  const formattedContent = await prettier.format(
    `${generatedContractComment} import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract"; \n\n
const deployedContracts = {${fileContent}} as const; \n\n export default deployedContracts satisfies GenericContractsDeclaration`,
    {
      parser: "typescript",
    }
  );

  fs.writeFileSync(targetPath, formattedContent);

  console.log(`📝 Successfully updated ${targetPath}`);
  console.log(`✨ ABI sync complete!`);
  
  // 验证新函数是否存在
  const contractNames = Object.keys(deployments);
  for (const contractName of contractNames) {
    const abi = deployments[contractName].abi;
    const functionNames = abi
      .filter((item: any) => item.type === "function")
      .map((item: any) => item.name);
    
    console.log(`\n📋 ${contractName} functions (${functionNames.length} total):`);
    console.log(`   ${functionNames.slice(0, 10).join(", ")}${functionNames.length > 10 ? "..." : ""}`);
    
    // 检查关键函数
    const keyFunctions = ["pauseListing", "resumeListing", "makeOffer", "acceptOffer", "getOffers"];
    const foundFunctions = keyFunctions.filter(fn => functionNames.includes(fn));
    
    if (foundFunctions.length > 0) {
      console.log(`   ✅ Found new functions: ${foundFunctions.join(", ")}`);
    }
  }
}

syncAbiToFrontend()
  .then(() => {
    console.log("\n🎉 Done!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Error:", error);
    process.exit(1);
  });
